#include <string.h>
#include "evaluate.h"
#include "../ast/astbuild.h"
#include "../ast/lexer.h"
#include "../ast/printbuf.h"
#include "../codegen/genname.h"
#include "../expr/literal.h"
#include "../type/alias.h"
#include "../type/assemble.h"
#include "../type/lookup.h"
#include "../type/reify.h"
#include "../type/subtype.h"
#include "../pass/expr.h"
#include "../pkg/package.h"
#include "ponyassert.h"
#include "../../libponyrt/mem/pool.h"

void evaluate_init(pass_opt_t* opt)
{
  if(opt->limit >= PASS_EVALUATE)
    builtin_init(opt);
}

void evaluate_done(pass_opt_t* opt)
{
  if(opt->limit >= PASS_EVALUATE)
    builtin_done(opt);
}

bool expr_constant(pass_opt_t* opt, ast_t* ast)
{
  pony_assert(ast_id(ast) == TK_CONSTANT);

  ast_t* expression = ast_child(ast);
  ast_settype(ast, control_type_add_branch(opt, NULL, expression));
  ast_t* type = ast_type(ast);
  if(is_typecheck_error(type))
    return false;

  // The '#' denotes that the expression is a compile-time expression, as such
  // it really must be val. We can only read values generated by the compiler.
  if(!is_type_literal(type))
  {
    ast_t* val_type = recover_type(type, TK_VAL);
    if(val_type == NULL)
    {
      ast_error(opt->check.errors, expression,
        "cannot recover compile-time object to val capability");
      return false;
    }

    ast_settype(expression, val_type);
    ast_free_unattached(type);
    ast_settype(ast, control_type_add_branch(opt, NULL, expression));
  }

  return true;
}

static bool evaluate(pass_opt_t* opt, ast_t* this, ast_t* expression, ast_t** result);

/*
 * Construct a mapping from the given lhs identifier to the rhs value. This
 * method assumes that all mappings are valid, the method is provided as a
 * convenience to extract the identifier name.
 */
static bool assign_value(pass_opt_t* opt, ast_t* this, ast_t* left,
  ast_t* right, ast_t** result)
{
  (void) opt;
  pony_assert(left != NULL);
  pony_assert(right != NULL);

  switch(ast_id(left))
  {
    case TK_VAR:
    case TK_VARREF:
    case TK_LET:
    case TK_FLET:
    case TK_PARAM:
      return ast_find_and_setvalue(left, ast_name(ast_child(left)), right,
                                   result);

    case TK_EMBEDREF:
    case TK_FLETREF:
    case TK_FVARREF:
    {
      AST_GET_CHILDREN(left, receiver, id);

      ast_t* evaluated_receiver;
      if(!evaluate(opt, this, receiver, &evaluated_receiver))
        return false;
      return ast_setvalue(evaluated_receiver, ast_name(id), right, result);
    }

    default:
      pony_assert(0);
      return false;
  }
}

// Bind a value so that it can be used in later compile-time expressions
static bool bind_value(pass_opt_t* opt, ast_t* this, ast_t* left, ast_t* right,
  ast_t** result)
{
  (void) opt;
  pony_assert(left != NULL);
  pony_assert(right != NULL);

  token_id left_id = ast_id(left);
  if(left_id == TK_VAR || left_id == TK_VARREF ||
     left_id == TK_FVAR || left_id == TK_FVARREF)
    return false;

  return assign_value(opt, this, left, right, result);
}

static bool construct_object_hygienic_name(printbuf_t* buf, pass_opt_t* opt,
  ast_t* type)
{

  switch(ast_id(type))
  {
    case TK_NOMINAL:
    {
      const char* type_name = genname_type(type);

      ast_t* def = (ast_t*)ast_data(type);
      if(ast_id(def) == TK_PRIMITIVE)
      {
        printbuf(buf, "%s", genname_instance(type_name));
        return true;
      }

      frame_push(&opt->check, ast_nearest(def, TK_PACKAGE));
      const char* s = package_hygienic_id(&opt->check);
      frame_pop(&opt->check);

      printbuf(buf, "%s_%s", type_name, s);
      return true;
    }

    case TK_TUPLETYPE:
    {
      printbuf(buf, "%dt", ast_childcount(type));
      ast_t* elem_type = ast_child(type);
      while (elem_type != NULL)
      {
        construct_object_hygienic_name(buf, opt, elem_type);
        elem_type = ast_sibling(elem_type);
      }
      return true;
    }

    default:
      pony_assert(0);
      return false;
  }
}

// Generate a hygienic name for an object of a given type
static const char* object_hygienic_name(pass_opt_t* opt, ast_t* type)
{
  printbuf_t* buf = printbuf_new();
  if(!construct_object_hygienic_name(buf, opt, type))
  {
    printbuf_free(buf);
    return NULL;
  }
  const char* r = stringtab(buf->m);
  printbuf_free(buf);
  return r;
}

bool construct_object(pass_opt_t* opt, ast_t* from, ast_t** result)
{
  pony_assert(from != NULL);
  ast_t* type = ast_type(from);
  const char* object_name = object_hygienic_name(opt, type);
  BUILD_NO_DECL(*result, from,
    NODE(TK_CONSTANT_OBJECT, AST_SCOPE ID(object_name)))
  ast_settype(*result, ast_dup(type));

  switch(ast_id(type))
  {
    case TK_NOMINAL:
    {

      const char* type_name = ast_name(ast_childidx(type, 1));
      ast_t* class_def = ast_get(from, type_name, NULL);
      pony_assert(class_def != NULL);

      if(ast_id(class_def) == TK_ACTOR)
      {
        ast_error(opt->check.errors, from,
                  "cannot construct compile-time actors");
        return false;
      }

      ast_t* members = ast_childidx(class_def, 4);
      ast_t* member = ast_child(members);
      while(member != NULL)
      {
        token_id member_id = ast_id(member);
        // Store all the fields that appear in this object, their values can be
        // found in the symbol table.
        if(member_id == TK_FVAR || member_id == TK_FLET || member_id == TK_EMBED)
        {
          sym_status_t s;
          ast_t* member_ast = ast_get(class_def, ast_name(ast_child(member)), &s);
          pony_assert(member_ast != NULL);
          pony_assert(ast_set(*result, ast_name(ast_child(member)), member_ast, s,
                      true));
          ast_append(*result, member);
        }

        member = ast_sibling(member);
      }

      return true;
    }

    case TK_TUPLETYPE:
    {
      size_t idx = 1;
      ast_t* elem = ast_child(from);
      while(elem != NULL)
      {
        printbuf_t* buf = printbuf_new();
        printbuf(buf, "_%d", idx);
        const char* idx_str = stringtab(buf->m);
        printbuf_free(buf);
        BUILD(idx_field, elem,
          NODE(TK_FLET, ID(idx_str) TREE(ast_type(elem)) NONE NONE));

        pony_assert(ast_set(*result, idx_str, idx_field, SYM_DEFINED, false));
        pony_assert(ast_setvalue(*result, idx_str, elem, NULL));
        ast_settype(idx_field, ast_type(elem));

        ast_append(*result, idx_field);
        elem = ast_sibling(elem);
        idx++;
      }
      return true;
    }

    default:
      pony_assert(0);
  }
  return false;
}

static bool evaluate_method(pass_opt_t* opt, ast_t* this, ast_t* expression,
  ast_t** result)
{
  pony_assert(expression != NULL);
  AST_GET_CHILDREN(expression, postfix, positional, named, question);

  // Named arguments have already been converted to positional
  pony_assert(ast_id(named) == TK_NONE);

  // Check if this is a parametric function type, the function lives one level
  // deeper. The deferred_reify later takes care of the parametric methods for
  // us.
  if(ast_id(ast_childidx(postfix, 1)) == TK_TYPEARGS)
    postfix = ast_child(postfix);

  AST_GET_CHILDREN(postfix, receiver, method_id);
  ast_t* receiver_type = ast_type(receiver);
  // Look through the this type arrow
  if((ast_id(receiver_type) == TK_ARROW) &&
    (ast_id(ast_child(receiver_type)) == TK_THISTYPE))
    receiver_type = ast_childidx(receiver_type, 1);

  // If there was no built-in then lookup the defintion of the function:
  // we push the package from where the function came from so that the lookup
  // proceeds as if we were in the correct package as we may, through private
  // methods within public methods, require access to private memebers.
  ast_t* def = ast_get(postfix, ast_name(ast_childidx(receiver_type, 1)), NULL);
  frame_push(&opt->check, ast_nearest(def, TK_PACKAGE));
  deferred_reification_t* method_def = lookup(opt, def, receiver_type,
                                              ast_name(method_id));
  pony_assert(method_def != NULL);
  ast_t* method = deferred_reify(method_def, method_def->ast, opt);
  pony_assert(method != NULL);
  deferred_reify_free(method_def);
  frame_pop(&opt->check);

  // Evaluate all the arguments and assign them to the repsective paramter
  // names, we also build up an array of the arguments in case we're going to
  // call a builtin.
  ast_t* parameters = ast_childidx(method, 3);
  ast_t* parameter = ast_child(parameters);
  ast_t* argument = ast_child(positional);
  ast_t* evaluated_args[ast_childcount(parameters)];
  size_t i = 0;
  while(argument != NULL && parameter != NULL)
  {
    ast_t* evaluated_arg;
    if(!evaluate(opt, this, argument, &evaluated_arg))
      return false;

    evaluated_args[i++] = evaluated_arg;
    if(!assign_value(opt, this, parameter, evaluated_arg, NULL))
      return false;
    parameter = ast_sibling(parameter);
    argument = ast_sibling(argument);
  }
  pony_assert(argument == NULL && parameter == NULL);

  // Lookup to see if we have a builtin method to evaluate the expression
  method_ptr_t builtin_method = builtin_lookup(opt, receiver, receiver_type,
                                               ast_name(method_id));

  ast_t* evaluated_receiver;
  if(!evaluate(opt, this, receiver, &evaluated_receiver))
    return false;

  if(builtin_method != NULL)
    return builtin_method(opt, evaluated_receiver, evaluated_args, result);

  ast_t* method_body = ast_childidx(method, 6);

  // Now in a position to evaluate the body
  switch(ast_id(postfix))
  {
    case TK_FUNREF:
      return evaluate(opt, evaluated_receiver, method_body, result);

    case TK_FUNCHAIN:
      if(!evaluate(opt, evaluated_receiver, method_body, result))
        return false;
      *result = evaluated_receiver;
      return true;

    case TK_NEWREF:
    {
      // If the receiver is an integer/bool type then, even if this is a
      // constructor, just execute the body as we don't want to construct any
      // object in this case (there would be nothing to put in it - so we just
      // use the raw values).
      ast_t* expression_type = ast_type(expression);
      if(is_integer(expression_type) || is_bool(expression_type))
        return evaluate(opt, evaluated_receiver, method_body, result);


      // If the method is a constructor then we need to build a compile time
      // object adding the values of the fields as the children and setting the
      // type to be the return type of the function body
      // Now run the constructor to initialise the fields etc.
      if(!construct_object(opt, expression, result))
        return false;

      ast_t* dontcare;
      if(!evaluate(opt, *result, method_body, &dontcare))
        return false;
      ast_free_unattached(dontcare);
      return true;
    }

    // We cannot evaluate compile-time behaviours, we shouldn't get here as we
    // cannot construct compile-time actors.
    case TK_BEREF:
      ast_error(opt->check.errors, postfix,
                "cannot evaluate compile-time behaviours");
      return false;

    default:
      pony_assert(0);
      return false;
  }
}

static bool evaluate(pass_opt_t* opt, ast_t* this, ast_t* expression,
  ast_t** result)
{
  pony_assert(expression != NULL);

  switch (ast_id(expression))
  {
    // Get and evaluate the inner expression
    case TK_CONSTANT:
      return evaluate(opt, this, ast_child(expression), result);

    // Literal cases where we can return the value
    case TK_NONE:
    case TK_TRUE:
    case TK_FALSE:
    case TK_INT:
    case TK_FLOAT:
    case TK_ERROR:
      *result = ast_dup(expression);
      return true;

    case TK_TUPLE:
    {
      ast_t* evaluated_tuple = ast_from(expression, TK_TUPLE);
      ast_settype(evaluated_tuple, ast_type(expression));
      ast_t* elem = ast_child(expression);
      while(elem != NULL)
      {
        ast_t* evaluated_elem;
        if(!evaluate(opt, this, elem, &evaluated_elem))
          return false;

        ast_append(evaluated_tuple, evaluated_elem);
        elem = ast_sibling(elem);
      }

      construct_object(opt, evaluated_tuple, result);
      return true;
    }

    case TK_TUPLEELEMREF:
    {
      AST_GET_CHILDREN(expression, receiver, idx)
      ast_t* evaluated_receiver;
      if(!evaluate(opt, this, receiver, &evaluated_receiver))
        return false;

      pony_assert(ast_id(idx) == TK_INT);
      lexint_t tmp;
      lexint_add64(&tmp, ast_int(idx), 1);
      printbuf_t* buf = printbuf_new();
      printbuf(buf, "_%s", lexint_string(&tmp));
      const char* idx_str = stringtab(buf->m);
      printbuf_free(buf);

      *result = ast_getvalue(evaluated_receiver, idx_str);
      pony_assert(*result != NULL);
      return true;
    }

    case TK_TYPEREF:
      *result = expression;
      return true;

    // FIXME:
    // String literals are a bit special; we want to construct an object with
    // all of the fields.
    case TK_STRING:
    {
      pony_assert(0);
    }

   // FVARREF may seem unintuitive to add but in fact it's safe due to the deep
   // immutability of val. Once we have constructed a compile-time object it
   // becomes val once it leaves the compile-time expression so the var field
   // is also constant.
   case TK_EMBEDREF:
   case TK_FLETREF:
   case TK_FVARREF:
    {
      AST_GET_CHILDREN(expression, receiver, id);
      ast_t* evaluated_receiver;
      if(!evaluate(opt, this, receiver, &evaluated_receiver))
        return false;

      *result = ast_getvalue(evaluated_receiver, ast_name(id));
      if(*result == NULL)
      {
        ast_error(opt->check.errors, expression,
          "field is not a compile-time expression");
        return false;
      }
      pony_assert(*result != NULL);
      return true;
    }

    // Variable lookups, checking that the variable has been bound to a value.
    // A missing binding means that the variable is not a compile-time variable.
    case TK_VARREF:
    case TK_PARAMREF:
    case TK_LETREF:
    {
      *result = ast_getvalue(expression, ast_name(ast_child(expression)));
      if(*result == NULL)
      {
        ast_error(opt->check.errors, expression,
          "variable is not a compile-time expression");
        return false;
      }
      pony_assert(*result != NULL);
      return true;
    }

    // Evaluating a destructive read
    case TK_ASSIGN:
    {
      AST_GET_CHILDREN(expression, left, right);

      ast_t* evaluated_right;
      if(!evaluate(opt, this, right, &evaluated_right))
        return false;

      return assign_value(opt, this, left, evaluated_right, result);
    }

    // Iterate through the sequence and evaluate in order, bailing if we error
    // or returning the last result
    case TK_SEQ:
    {
      ast_t* evaluated;
      for(ast_t* p = ast_child(expression); p != NULL; p = ast_sibling(p))
      {
        if(!evaluate(opt, this, p, &evaluated))
          return false;
      }
      *result = evaluated;
      return true;
    }

    case TK_CALL:
      return evaluate_method(opt, this, expression, result);

    case TK_THIS:
    {
      *result = this != NULL ? this : expression;
      return true;
    }

    case TK_IF:
    case TK_ELSEIF:
    {
      AST_GET_CHILDREN(expression, condition, then_branch, else_branch);
      ast_t* evaluated_condition;
      if(!evaluate(opt, this, condition, &evaluated_condition))
        return false;

      pony_assert(ast_id(evaluated_condition) == TK_TRUE ||
                  ast_id(evaluated_condition) == TK_FALSE);

      return ast_id(evaluated_condition) == TK_TRUE ?
            evaluate(opt, this, then_branch, result):
            evaluate(opt, this, else_branch, result);
    }

    case TK_WHILE:
    {
      AST_GET_CHILDREN(expression, condition, then_body, else_body);
      ast_t* evaluated_condition;
      if(!evaluate(opt, this, condition, &evaluated_condition))
        return false;

      pony_assert(ast_id(evaluated_condition) == TK_TRUE ||
                  ast_id(evaluated_condition) == TK_FALSE);

      // The condition didn't hold on the first iteration so we evaluate the
      // else
      if(ast_id(evaluated_condition) == TK_FALSE)
        return evaluate(opt, this, else_body, result);

      // The condition held so evaluate the while returning the iteration
      // result as the evaluated result
      while(ast_id(evaluated_condition) == TK_TRUE)
      {
        if(!evaluate(opt, this, then_body, result) ||
           !evaluate(opt, this, condition, &evaluated_condition))
          return false;

        pony_assert(ast_id(evaluated_condition) == TK_TRUE ||
                    ast_id(evaluated_condition) == TK_FALSE);
      }

      return true;
    }

    case TK_TRY:
    {
      // Evaluate the try expression but this may result in a TK_ERROR result,
      // so test if this is the case after evaluation, if so evaluate the else
      // branch
      AST_GET_CHILDREN(expression, try_body, else_body);
      if(!evaluate(opt, this, try_body, result))
        return false;

      if(ast_id(*result) == TK_ERROR)
        return evaluate(opt, this, else_body, result);

      return true;
    }

    case TK_IS:
    {
      AST_GET_CHILDREN(expression, lhs, rhs);

      ast_t* evaluated_lhs, *evaluated_rhs;
      if(!evaluate(opt, this, lhs, &evaluated_lhs) ||
         !evaluate(opt, this, rhs, &evaluated_rhs))
        return false;

      // If the comparison is based on objects then we can check name equality
      if(ast_id(evaluated_lhs) == TK_CONSTANT_OBJECT)
      {
        const char* lhs_name = ast_name(ast_child(evaluated_lhs));
        const char* rhs_name = ast_name(ast_child(evaluated_rhs));
        BUILD_NO_DECL(*result, expression,
          NODE(lhs_name == rhs_name ? TK_TRUE : TK_FALSE));
        return true;
      }

      // Otherwise, it's some builtin, in which case the easiest approach is
      // just to call the "eq" builtin method for the type.
      method_ptr_t builtin_method = builtin_lookup(opt, lhs, ast_type(lhs),
                                                   stringtab("eq"));
      if(builtin_method == NULL)
      {
        ast_error(opt->check.errors, expression,
          "unsupported compile-time comparison\n");
        return false;
      }

      return builtin_method(opt, evaluated_lhs, &evaluated_rhs, result);
    }

    case TK_CONSUME:
      return evaluate(opt, this, ast_childidx(expression, 1), result);

    case TK_RECOVER:
      return evaluate(opt, this, ast_childidx(expression, 1), result);

    default:
      ast_error(opt->check.errors, expression,
        "expression was not a compile-time expression");
#ifdef DEBUG
      ast_error_continue(opt->check.errors, expression,
        "unsupported expression token was %s", lexer_print(ast_id(expression)));
#endif
      return false;
  }

  pony_assert(0);
  return false;
}

ast_result_t pass_evaluate(ast_t** astp, pass_opt_t* options)
{
  ast_t* ast = *astp;

  if(ast_id(ast) == TK_CONSTANT)
  {
    ast_t* result;
    if(!evaluate(options, NULL, ast, &result))
    {
      pony_assert(errors_get_count(options->check.errors) > 0);
      return AST_ERROR;
    }

    if(ast_id(result) == TK_ERROR)
    {
      ast_error(options->check.errors, ast,
                "unresolved error occurred during evaluation");
      ast_error_continue(options->check.errors, result,
                         "error originated here");
      return AST_ERROR;
    }

    pony_assert(result != NULL);

    if(ast_id(ast_parent(ast)) == TK_ASSIGN)
      bind_value(options, NULL, ast_previous(ast), result, NULL);
    ast_replace(astp, result);
  }

  return AST_OK;
}

ast_result_t pre_pass_evaluate(ast_t** astp, pass_opt_t* options)
{
  (void) options;
  ast_t* ast = *astp;

  if(ast_id(ast) == TK_FLET || ast_id(ast) == TK_EMBED)
  {
    AST_GET_CHILDREN(ast, f_id, f_type, f_init);
    if(ast_id(f_init) != TK_CONSTANT)
      return AST_OK;

    ast_t* result;
    if(!evaluate(options, NULL, f_init, &result))
    {
      pony_assert(errors_get_count(options->check.errors) > 0);
      return AST_ERROR;
    }

    pony_assert(bind_value(options, NULL, ast, result, NULL));
    ast_swap(f_init, ast_from(f_init, TK_NONE));
  }

  return AST_OK;
}
